### ISSUE TITLE
Quiet mode doesn't allow to use :

### ISSUE THREAD

**Issue by bijancn** [gsec/eZchat#22]
Steps to reproduce:
python ez_chat.py -q
press :
gives

```
Traceback (most recent call last):
  File "ez_cli.py", line 836, in <module>
    loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 339, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 669, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 706, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 390, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 490, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1124, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 839, in keypress
    return self._original_widget.keypress((maxcol,maxrow-top-bottom), key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 2265, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1583, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 385, in keypress
    return self._original_widget.keypress((maxcol, self.height), key)
  File "ez_cli.py", line 123, in keypress
    ez_cli.vimedit.keypress((size[0],), key)
  File "ez_cli.py", line 545, in keypress
    self.command_dict[key]()
  File "ez_cli.py", line 444, in cmd_enter_cmdline
    urwid.emit_signal(self, 'command_line', self, ':')
  File "/usr/local/lib/python2.7/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/local/lib/python2.7/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "ez_cli.py", line 708, in command_line_mode
    self.command_and_status.set_focus(1)
AttributeError: 'VimCommandLine' object has no attribute 'set_focus'
```

Possible Solution: For now quiet sets `ep.cli_status_height = 0`. This also prevents the use of commands, I guess. It would be better to check for something like `ep.verbose` when sending something to the status line. It is also more standard to set `-v` or `--verbose` instead of quiet.

**Comment by JNicL** [comment]
fixed.
